#!/usr/bin/env bun
// Generate src/data/insights.ts from scripts/insights-source.json (X Articles by
// @quack_builder, pulled via the API `article` field — article.plain_text holds
// the full body). Re-run after refreshing the source:
//   bun run scripts/gen-insights.ts
//
// To refresh the source itself (uses X API quota — free tier is tight):
//   source ~/.claude/credentials/twitter.env
//   python3 -c "..."  # tweet.fields=article on /2/users/<id>/tweets ; keep article.{title,plain_text,preview_text}
//
// Body strings are embedded with JSON.stringify so long Chinese text with
// quotes / newlines escapes safely.

import { readFileSync, writeFileSync } from 'node:fs';

interface SrcArticle { id: string; date: string; likes: number; title: string; plain_text: string; preview: string; }

// Per-article presentation metadata, keyed by tweet id. Only ids listed here are
// published — this is the include-list (off-topic posts are simply omitted).
const META: Record<string, { slug: string; type: string; cover: string; readTime: string; featured?: boolean }> = {
  '2049767255492403206': { slug: 'bittensor-ecosystem-guide',   type: '指南', cover: 'cover-1', readTime: '30 分钟', featured: true },
  '2050536096178864324': { slug: 'bittensor-bitcoin-of-ai-cn',  type: '译文', cover: 'cover-2', readTime: '18 分钟' },
  '2050911749864575127': { slug: 'bittensor-bitcoin-of-ai-en',  type: 'Essay', cover: 'cover-2', readTime: '20 min' },
  '2052782487970160820': { slug: 'tao-and-the-dao',             type: '随笔', cover: 'cover-6', readTime: '24 分钟' },
  '2056281732740206731': { slug: 'bittensor-mechanics-part-1',  type: '深度', cover: 'cover-4', readTime: '18 分钟' },
  '2057421040649982326': { slug: 'bittensor-mechanics-part-2',  type: '深度', cover: 'cover-4', readTime: '20 分钟' },
};

const HANDLE = 'quack_builder';

function lead(preview: string): string {
  const oneLine = preview.replace(/\s+/g, ' ').trim();
  if (oneLine.length <= 96) return oneLine;
  return oneLine.slice(0, 94).replace(/[，,。.、:：]$/, '') + '…';
}

function coverText(title: string): string {
  // short mono label for the gradient tile
  return title.replace(/\s+/g, ' ').slice(0, 22);
}

const src: SrcArticle[] = JSON.parse(readFileSync('scripts/insights-source.json', 'utf8'));
const rows = src
  .filter((a) => META[a.id])
  .sort((a, b) => b.date.localeCompare(a.date)); // newest first

const lines: string[] = [];
lines.push('// Insights registry — real X Articles by @quack_builder.');
lines.push('// AUTO-GENERATED by scripts/gen-insights.ts from scripts/insights-source.json.');
lines.push('// DO NOT EDIT BY HAND — edit the source JSON / META map and re-run the script.\n');
lines.push('export interface Insight {');
lines.push('  slug: string;');
lines.push('  title: string;');
lines.push('  lead: string;');
lines.push('  body: string;            // full text; blank lines separate paragraphs');
lines.push('  type: string;');
lines.push('  readTime: string;');
lines.push('  cover: string;');
lines.push('  coverText: string;');
lines.push('  author: string;');
lines.push('  authorHandle?: string;');
lines.push('  date: string;');
lines.push('  sourceUrl?: string;');
lines.push('  featured?: boolean;');
lines.push('  rich?: boolean;');
lines.push('}\n');
lines.push('export const insights: Insight[] = [');
for (const a of rows) {
  const m = META[a.id];
  const date = a.date.replace(/-/g, '·');
  lines.push('  {');
  lines.push(`    slug: ${JSON.stringify(m.slug)},`);
  lines.push(`    title: ${JSON.stringify(a.title.trim())},`);
  lines.push(`    lead: ${JSON.stringify(lead(a.preview || a.plain_text))},`);
  lines.push(`    body: ${JSON.stringify(a.plain_text.trim())},`);
  lines.push(`    type: ${JSON.stringify(m.type)}, readTime: ${JSON.stringify(m.readTime)},`);
  lines.push(`    cover: ${JSON.stringify(m.cover)}, coverText: ${JSON.stringify(coverText(a.title))},`);
  lines.push(`    author: ${JSON.stringify(HANDLE)}, authorHandle: ${JSON.stringify('@' + HANDLE)},`);
  lines.push(`    date: ${JSON.stringify(date)},`);
  lines.push(`    sourceUrl: ${JSON.stringify(`https://x.com/${HANDLE}/status/${a.id}`)},`);
  if (m.featured) lines.push('    featured: true,');
  lines.push('  },');
}
lines.push('];\n');
lines.push('export function getInsight(slug: string): Insight | undefined {');
lines.push('  return insights.find((i) => i.slug === slug);');
lines.push('}');

writeFileSync('src/data/insights.ts', lines.join('\n') + '\n');
console.log(`Generated src/data/insights.ts with ${rows.length} articles.`);
for (const a of rows) console.log(`  ${a.date}  ${META[a.id].slug}  (${a.plain_text.length} chars)`);
